### PR TITLE
Fix references when rules are unused, and fix missing cloneExpr

### LINKED ISSUE #70: Build failure only when --optimize-grammar is set; grammar with not referenced rule
The following grammar results in build failure, if generated with `--optimize-grammar`. The same grammar builds with out problem, if the option is not set.

Minimal example:

```
X ← z:Z
Y ← Z
Z ← ('Z' { return nil, nil })?
```

Build error:

```
(*parser).callonZ3 undefined (type *parser has no method callonZ3)
```

### PR DESCRIPTION
**Pull request by mna**
This fixes #70 and an additional issue with optimization where a clone was missing, resulting in build errors on otherwise valid grammars.

This includes the changes in #71 .

### CODE REVIEW

File: ast/ast.go [hunk 1]
```diff
@@ -166,7 +166,7 @@ func (a *ActionExpr) Pos() Pos { return a.p }
 
 // String returns the textual representation of a node.
 func (a *ActionExpr) String() string {
-	return fmt.Sprintf("%s: %T{Expr: %v, Code: %v}", a.p, a, a.Expr, a.Code)
+	return fmt.Sprintf("%s: %T{Expr: %v, Code: %v, FuncIx: %d, ID: %p}", a.p, a, a.Expr, a.Code, a.FuncIx, a)
```
Comment (mna) [inline ast/ast.go]: I had added this for easier debugging (and noticing the missing clone), let me know if you'd rather have it removed (this could be considered a breaking change, but I think that's a stretch :) )

File: Makefile [hunk 2]
```diff
@@ -154,6 +154,12 @@ $(TEST_DIR)/issue_65/optimized/issue_65.go: $(TEST_DIR)/issue_65/issue_65.peg $(
 $(TEST_DIR)/issue_65/optimized-grammar/issue_65.go: $(TEST_DIR)/issue_65/issue_65.peg $(BINDIR)/pigeon
 	$(BINDIR)/pigeon -nolint -optimize-grammar $< > $@
 
+$(TEST_DIR)/issue_70/issue_70.go: $(TEST_DIR)/issue_70/issue_70.peg $(BINDIR)/pigeon
```
Comment (breml) [inline Makefile]: Why have you removed the additional lines for the optimized parsers? (see [here](https://github.com/mna/pigeon/blob/0cb2d5b52ca30953f163b431db5ffba5101cffe6/Makefile#L160-L164))?

File: ast/ast.go (hunk 1 above)
Comment (breml) [reply ast/ast.go]: Please remove it.

File: Makefile (hunk 2 above)
Comment (mna) [reply Makefile]: Probably a mistake when fixing the makefile conflict. Added them back.

File: ast/ast.go (hunk 1 above)
Comment (mna) [reply ast/ast.go]: Done.

**Comment by breml** [comment]
@mna Thank Martin, LGTM.
